# Generated by Django 3.0.2 on 2020-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_web_graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('btc_count', models.IntegerField()),
                ('btc_mining_diff', models.FloatField()),
            ],
        ),
    ]
